name = "misskey-registration-filter"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "9c19c252207c4fcca434e044025b095e"
